controllers:
    resource: ../src/Controller/
    type: attribute

favicon:
    path: /favicon.ico
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirect
    defaults:
        path: /favicon.ico
        permanent: true
